### ISSUE TITLE
User guide instructions don't mention osvvm.do script

### ISSUE THREAD

**Issue by kwhms** [OSVVM/OSVVM#21]
I just cloned OSVVM and as part of getting started, I opened up RandomPkg_user_guide.pdf and jumped to section 14 for compile instructions. I tried a straightforward compile of said files but got an error because of the work library reference. 

My suggestion to update instructions to reference running osvvm.do since that seamlessly replaces work with osvvm and is readily available as part of the git clone.

**Comment by JimLewis** [comment]
Updated documentation so that it all refers to the osvvm release guide which in turn references osvvm.do
