### ISSUE TITLE
Alert FAILURE RandomPkg

### ISSUE THREAD

**Issue by slaweksiluk** [OSVVM/OSVVM#30]
During tests  with usage of RandomPType sometimes I receive following error:
```
%% Alert FAILURE RandomPkg.(RandIntV | RandRealV | RandTimeV): Unique > number of values available at 35 ns

%% Alert Stop Count on FAILURE reached at 35 ns 
%% DONE  FAILED  AlertLogTop  Total Error(s) = 1  Failures: 1  Errors: 0  Warnings: 0  at 35 ns
```
what does it mean?

**Comment by JimLewis** [comment]
It would be easier to comment if you would share what you are trying to do and your code.

RandIntV | RandRealV | RandTimeV are overloaded.   The simplest form is:
```
-- Generate 10 integer values in the range 0 to 255 
IntV(1 to 10) := RV.RandIntV(0, 255, 10) ;
```
However there are times when you want to not repeat either the last value or some number of the previous values.   This is handled by:
```
-- Generate 10 integer values in the range 0 to 255, do repeat the last value 
IntV(1 to 10) := RV.RandIntV(0, 255, 1, 10) ;
```

What happened in your case is that you asked it go create more unique values that are in the set of numbers you are selecting between.   The following would also generate the same error:
```
IntV(1 to 10) := RV.RandIntV(0, 4, 10, 10) ;
```

This is discussed in the user guide section 7 Randomizing Sets of Values.
