### ISSUE TITLE
AlertLogPkg:   IncAlertCount Procedure should call stop with exit code 1

### ISSUE THREAD

**Issue by SkydiverTricky** [OSVVM/OSVVM#38]
Shouldnt  procedure IncAlertCount () exit with code 1? 
The alert procedure exits with code 1.
This way CI can know if a test has failed without having to scrub the log?

Or maybe have a config item to set the exit code?

**Comment by m-kru** [comment]
I also think that exit status code should not be 0 in such case.

**Comment by JimLewis** [comment]
Planned for next revision

**Comment by JimLewis** [comment]
I should clariify, AlertLogPkg will call stop with the current ErrorCount:    
std.env.stop(ErrorCount)

ErrorCount is a global variable in the AlertLogPkg protected type.  In some simulators it can be traced.   It can also be optionally be printed following Alert and before the Alert Level

**Comment by JimLewis** [comment]
Released in 2020.05
