### ISSUE TITLE
Random values not sequential

### ISSUE THREAD

**Issue by sjaeckel** [OSVVM/OSVVM#39]
I recently discovered that `RandSlv(16)` does not return the same as calling `RandSlv(8)` twice and I wanted to ask if that's intended? I couldn't find anything regarding this in the documentation, probably I missed it?

**Comment by JimLewis** [comment]
This is normal.  

RandSlv(16) uses the current seed and randomize a 16 bit number.   The base randomization is 32 bits, so this is done with a single randomization.

The first RandSlv(8) uses the current seed to randomize an 8 bit number.   The second RandSlv(8) uses the seed updated by the first randomization to randomize an 8 bit number.   

Hence, in your RandSlv(16) you changed the seed once.   In your RandSlv(8) you updated the seed twice.  Not only will these produce different results, but if you replaced the RandSlv(16) by two separate RandSlv(8) you change the state of the seed after the test completes - which in turn will impact what the entire test does.

OTOH, RandSlv(48) will do two randomizations to product a 48 bit number.   However, this number need not be the same as two separate RandSlv(24).  OTOH if the seed value was the same at the start of these operations, the final seed value after both of these have occurred will be the same.

At the end of the day, what pseudo random does guarantee, is that if you start with the same seed value and do the same sequence, you will get the same values - and hence, the same test.
