### ISSUE TITLE
ScoreboardGenericPkg: Removal of whitespace characters before "Received:"

### ISSUE THREAD

**Issue by SebDunst** [OSVVM/OSVVM#49]
Hi Jim,

I am wondering why there are 3 whitespace characters in procedure "LocalCheck" before printout of the word "Received:" (line 992).

This is only a visual issue, but in my opinion without this whitespace the logfile's output would be more consistent.

Best regards,
Sebastian

**Comment by JimLewis** [comment]
This was addressed in a recent release.
